List<String> magic = [
  "Music is life,",
  "Feel the groove,",
  "Spin that track,",
  "Your beat, your flow,",
  "Make every note count,",
  "Sing your heart out,",
  "Turn the volume up,",
  "Find your melody,",
  "Every song’s a story,",
  "Keep calm and play music,",
  "Let the music speak,",
  "Press play and relax,",
  "Discover new tunes,",
  "Your soundscape awaits,",
  "Dance like nobody’s watching,",
  "Unwind with music,",
  "Your playlist, your rules,",
  "Time to get musical,",
  "Harmonize your day,",
  "The rhythm is calling,",
  "Feel good beats for you,",
  "Catch the melody,",
  "Music heals all,",
  "Ready to jam out,",
  "Put your headphones on,",
  "Let’s make some noise,",
  "Soundtrack your moments,",
  "Keep the good vibes flowing,",
  "Play, pause, repeat,",
  "Elevate your spirit,",
  "A song a day keeps worries away,",
  "Your music journey starts now,",
  "Find your favorite beat,",
  "Create your vibe,",
  "Tune in and turn up,",
  "Music that moves you,",
  "Let’s get lost in music,",
  "Playlist perfection,",
  "Sing it loud,",
  "Celebrate sound,",
  "Good tunes, great day,",
  "Feel the bass drop,",
  "Music in your soul,",
  "Ready for your next track,",
  "Keep your feet moving,",
  "Sound waves for your soul,",
  "The beat goes on,",
  "Play your heart out,",
  "Your music, your moment,",
  "Vibes only,",
  "Feel the music magic,",
  "Sing your story,",
  "Turn up your mood,",
  "Music to brighten your day,",
  "Your rhythm awaits,",
  "Hit the high notes,",
  "Find your sonic bliss,",
  "Songs that speak to you,",
  "Let’s groove tonight,",
  "Your jam session starts here,",
  "Keep the music alive,",
  "Play your favorite hits,",
  "Feel the harmony,",
  "Discover your next favorite,",
  "Unleash the music lover in you,",
  "Good music, good mood,",
  "The world’s your stage,",
  "Turn music into memories,",
  "Soundtrack your life,",
  "Live, love, listen,",
  "Your playlist, your vibe,",
  "Find your perfect beat,",
  "Jam out anytime,",
  "Feel every beat drop,",
  "Music for every moment,",
  "Let the music move you,",
  "Sing, dance, repeat,",
  "Your soundtrack of joy,",
  "Vibes curated for you,",
  "Play your heart’s desire,",
  "Find peace in sound,",
  "Music brings us together,",
  "Enjoy the rhythm,",
  "Keep the beat alive,",
  "Tune in to happiness,",
  "Life’s better with music,",
  "Start your music journey,",
  "The beat is yours to own,",
  "Music that inspires,",
  "Let your heart sing,",
  "Feel the groove, feel alive,",
  "Your personal concert,",
  "Songs that move you,",
  "Create memories with music,",
  "Hit the play button,",
  "Let’s get musical,",
  "Let’s vibe,",
  "Play it loud,",
  "Feel the beat,",
  "Your vibe, your playlist,",
  "Good tunes ahead,",
  "Music’s calling,",
  "Hit play,",
  "Let’s jam,",
  "Welcome back,",
  "Sound on, world off,",
  "Press play,",
  "What’s the mood today,",
  "Start the vibe,",
  "Tap to tune in,",
  "Turn it up,",
  "Ready to groove,",
  "Let music flow,",
  "Make today musical,",
  "Sing it out,",
  "A song for every mood,",
  "Feel the rhythm,",
  "Jam mode: ON,",
  "You deserve good music,",
  "Music makes it better,",
  "Your ears, your rules,",
  "Mood = Music,",
  "Let the tunes roll,",
  "Beats before stress,",
  "One click to chill,",
  "Play your vibe,",
  "It's music time,",
  "Drown the noise,",
  "Feel every note,",
  "Let’s escape in music,",
  "Your playlist, your world,",
  "Start the show,",
  "Pick your sound,",
  "Time to tune in,",
  "Unlock the beat,",
  "Let the track speak,",
  "Groove starts now,",
  "Your day needs music,",
  "Dance it out,",
  "Chill mode on,",
  "Rhythm ready,",
  "Catch the vibe,",
  "Track of the day,",
  "Just vibes,",
  "Turn up the energy,",
  "Let the beat drop,",
  "Streaming happiness,",
  "Let’s soundtrack your day,",
  "Tap in, tune out,",
  "Every beat counts,",
  "No bad days with music,",
  "You’ve got great taste,",
  "Vibe with us,",
  "Spin something new,",
  "Hear the moment,",
  "Elevate with music,",
  "Hit repeat,",
  "Perfect time to listen,",
  "That’s a vibe,",
  "Let’s get melodic,",
  "Your music zone,",
  "Welcome to your sound,",
  "Cue the music,",
  "Find your rhythm,",
  "Pick a track,",
  "Your soundtrack starts now,",
  "Flow with the beats,",
  "Amp it up,",
  "Play it your way,",
  "Make it musical,",
  "Favorite time: Music time,",
  "Go full volume,",
  "Let it move you,",
  "You + music = 🔥,",
  "A vibe a day keeps stress away,",
  "Every track tells a story,",
  "Fuel your mood,",
  "Good music, good mood,",
  "This one’s for you,",
  "Play something epic,",
  "It’s your music break,",
  "The beat is yours,",
  "Lights, camera, music,",
  "Playlist unlocked,",
  "Embrace the sound,",
  "Rewind and replay,",
  "Lost in sound,",
  "Your escape starts now,",
  "Sing along,",
  "Drop the beat,",
  "One tap to vibe,",
  "You’re the DJ,",
  "Crank it up,",
  "Melody in motion,",
  "Your kind of rhythm,",
  "Let music heal,",
  "Find peace in music,",
  "Sounds like a great day,",
  "Feel the beat drop,",
  "Your music, your vibe,",
  "Let the rhythm guide you,",
  "Turn up the volume,",
  "Find your flow,",
  "Sing your soul out,",
  "Dance like no one's watching,",
  "Every note matters,",
  "Music is your magic,",
  "Jam to your own tune,",
  "Your playlist, your story,",
  "Let the music heal,",
  "Feel alive with sound,",
  "Make today musical,",
  "Sing along,",
  "Your beats, your power,",
  "Find peace in music,",
  "Music moves you,",
  "Tune in and chill,",
  "Create your soundtrack,",
  "Feel the vibes,",
  "Let sound lift you,",
  "Rhythm in your heart,",
  "Your jam is waiting,",
  "Good vibes only,",
  "Music is your escape,",
  "Hear your happiness,",
  "Turn moments to music,",
  "Your beat, your moment,",
  "Sing it loud,",
  "Find your groove,",
  "Songs for your soul,",
  "Feel the melody,",
  "Dance to your heart,",
  "Your rhythm rocks,",
  "Music makes you shine,",
  "Jam session starts now,",
  "Soundtrack your life,",
  "Let the music flow,",
  "Play your heart out,",
  "Feel the bass,",
  "Music in your veins,",
  "Sing your story,",
  "Keep the beat alive,",
  "Your tunes, your time,",
  "Make noise,",
  "Let music inspire,",
  "Turn up your day,",
  "Feel every chord,",
  "Your music moment,",
  "Play and smile,",
  "Sing with passion,",
  "Find joy in music,",
  "Your rhythm awaits,",
  "Feel good tunes,",
  "Soundtrack of joy,",
  "Dance with life,",
  "Music is your friend,",
  "Turn up happiness,",
  "Every beat counts,",
  "Sing with your heart,",
  "Create your vibe,",
  "Feel music’s power,",
  "Jam to the rhythm,",
  "Find your beat,",
  "Sing your mood,",
  "Your music, your day,",
  "Make every song count,",
  "Dance like crazy,",
  "Feel the groove,",
  "Music lifts you up,",
  "Sing, dance, repeat,",
  "Your beat, your rules,",
  "Turn moments into music,",
  "Sing your dreams,",
  "Feel the sound waves,",
  "Play your favorites,",
  "Music fuels your soul,",
  "Dance through the day,",
  "Sing loud and proud,",
  "Your soundtrack of life,",
  "Feel alive with music,",
  "Jam on,",
  "Turn up the fun,",
  "Find your harmony,",
  "Sing for joy,",
  "Your vibe, your music,",
  "Music is your power,",
  "Feel the rhythm deep,",
  "Dance your heart out,",
  "Sing your favorite tune,",
  "Your music journey starts here,",
  "Feel good, sound good,",
  "Jam with passion,",
  "Let the music speak,",
  "Turn up your smile,",
  "Sing with soul,",
  "Your playlist rocks,",
  "Music is your energy,",
  "Dance in the moment,",
  "Feel every beat,",
  "Sing your story,",
  "Jam all day,",
  "Turn music into memories,",
  "Feel the bass line,",
  "Sing for your soul,",
  "Your rhythm, your day,",
  "Play with passion,",
  "Music lights your way,",
  "Dance to the beat,",
  "Sing your happiness,",
  "Your soundtrack awaits,",
  "Feel the music vibes,",
  "Jam on the go,",
  "Turn your day musical,",
  "Sing with heart,",
  "Your music, your mood,",
  "Feel the sound,",
  "Dance like a star,",
  "Sing your tune,",
  "Jam your way,",
  "Turn up the groove,",
  "Feel the joy of music,",
  "Sing your happiness,",
  "Your playlist, your flow,",
  "Music for your soul,",
  "Dance your worries away,",
  "Sing loud, sing proud,",
  "Your beat, your world,",
  "Feel the music love,",
  "Jam out loud,",
  "Turn music into magic,",
  "Sing with your heart,",
  "Your soundtrack, your life,",
  "Feel alive with sound,",
  "Dance to your rhythm,",
  "Sing your spirit,",
  "Jam with joy,",
  "Turn moments into music,",
  "Feel the beat inside,",
  "Sing your favorite song,",
  "Your music, your soul,",
  "Dance in your own way,",
  "Sing with energy,",
  "Jam all night,",
  "Turn up your passion,",
  "Feel the rhythm in you,",
  "Sing your happiness,",
  "Your playlist, your power,",
  "Music is your language,",
  "Dance like a dream,",
  "Sing your truth,",
  "Jam to the beat,",
  "Turn up the love,",
  "Feel music’s magic,",
  "Sing your heart’s song,",
  "Your soundtrack, your vibe,",
  "Dance through life,",
  "Sing with joy,",
  "Jam to your soul,",
  "Turn moments into memories,",
  "Feel the beat move you,",
  "Sing your favorite tune,",
  "Your music, your energy,",
  "Dance your heart free,",
  "Sing with your soul,",
  "Jam to the rhythm of life,",
  "Turn your day into music,",
  "Feel the sound of joy,",
  "Sing your story loud,",
  "Your playlist, your happiness,",
  "Dance with your spirit,",
  "Sing your dream,",
  "Jam with your heart,",
  "Turn up the beat,",
  "Feel the music in you,",
  "Sing your soul’s tune,",
  "Your soundtrack, your joy,",
  "Dance like nobody’s watching,",
  "Sing your happiness,",
  "Jam with passion,",
  "Turn moments into songs,",
  "Feel the rhythm,",
];
